//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travelancar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int id_user { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public string Sex { get; set; }
        public short joined { get; set; }
        public string street { get; set; }
        public string PHONENO { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string username { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string password { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
